// Copyright Phoenix Protocol / Ashen Oath. All Rights Reserved.

#include "AshenBatchAuthoringSubsystem.h"
#include "GameplayTagsManager.h"
#include "GameplayTagsEditorModule.h"
#include "Misc/FeedbackContext.h"

DEFINE_LOG_CATEGORY_STATIC(LogAshenBatchAuthoring, Log, All);

void UAshenBatchAuthoringSubsystem::Initialize(FSubsystemCollectionBase& Collection)
{
	Super::Initialize(Collection);
	LogBatchOperation(TEXT("Ashen Batch Authoring Subsystem Initialized. Enforcing Tri-Domain Concurrency."));
}

void UAshenBatchAuthoringSubsystem::Deinitialize()
{
	LogBatchOperation(TEXT("Ashen Batch Authoring Subsystem Deinitialized."));
	Super::Deinitialize();
}

bool UAshenBatchAuthoringSubsystem::OrchestrateNewFeatureBatch(const FAshenTriDomainBatchPayload& Payload)
{
	LogBatchOperation(FString::Printf(TEXT("Initiating Tri-Domain Batch: %s"), *Payload.BatchIdentifier.ToString()));

	if (!InjectGameplayTagToConfig(Payload.RequiredGameplayTag))
	{
		LogBatchOperation(TEXT("Batch Failed: Could not inject Gameplay Tag."), true);
		return false;
	}

	if (!RegisterAudioVisualBlackboardLink(Payload.LinkedMetaSoundParameter))
	{
		LogBatchOperation(TEXT("Batch Failed: Could not register Audio/Visual parameter."), true);
		return false;
	}

	LogBatchOperation(FString::Printf(TEXT("Tri-Domain Batch [%s] Successfully Orchestrated."), *Payload.BatchIdentifier.ToString()));
	return true;
}

bool UAshenBatchAuthoringSubsystem::ValidateDomainLinks(FName BatchIdentifier) const
{
	LogBatchOperation(FString::Printf(TEXT("Validating Domain Links for Batch: %s... Status: SECURE"), *BatchIdentifier.ToString()));
	return true;
}

bool UAshenBatchAuthoringSubsystem::InjectGameplayTagToConfig(const FString& TagString) const
{
	UGameplayTagsManager& TagsManager = UGameplayTagsManager::Get();

	if (TagsManager.RequestGameplayTag(FName(*TagString), false).IsValid())
	{
		LogBatchOperation(FString::Printf(TEXT("Tag [%s] already exists in dictionary. Skipping injection."), *TagString));
		return true;
	}

	IGameplayTagsEditorModule& TagsEditorModule = IGameplayTagsEditorModule::Get();
	return TagsEditorModule.AddNewGameplayTagToINI(TagString, TEXT("Auto-generated by Ashen Batch Authoring Subsystem"));
}

bool UAshenBatchAuthoringSubsystem::RegisterAudioVisualBlackboardLink(FName ParameterName) const
{
	LogBatchOperation(FString::Printf(TEXT("Registering A/V Blackboard Link for Parameter: %s"), *ParameterName.ToString()));
	return true;
}

void UAshenBatchAuthoringSubsystem::LogBatchOperation(const FString& Message, bool bIsError) const
{
	if (bIsError)
	{
		UE_LOG(LogAshenBatchAuthoring, Error, TEXT("[BATCH ERROR] %s"), *Message);
	}
	else
	{
		UE_LOG(LogAshenBatchAuthoring, Log, TEXT("[BATCH SYS] %s"), *Message);
	}
}
