// Copyright Phoenix Protocol / Ashen Oath. All Rights Reserved.
#pragma once

#include "CoreMinimal.h"
#include "UObject/NoExportTypes.h"
#include "Narrative/AshenIdentityCompilerTypes.h"
#include "Narrative/AshenIdentityGovernanceBalanceDataAsset.h"
#include "AshenIdentityGovernanceValidator.generated.h"

/**
 * UAshenIdentityGovernanceValidator
 *
 * C++ Zero-Trust Firewall processing offline SLM JSON outputs at Heartstone campfires.
 * Deserializes JSON, validates schema, audits memory provenance against ActiveImprintBuffer,
 * enforces hard delta clamping, and calculates asymmetric memory decay (RIC-003).
 */
UCLASS(BlueprintType)
class ASHENOATH_API UAshenIdentityGovernanceValidator : public UObject
{
	GENERATED_BODY()

public:
	UAshenIdentityGovernanceValidator();

	/** Fallback hard runtime constraints protecting state integrity */
	static constexpr float DEFAULT_MAX_ALLOWABLE_DELTA = 0.25f;
	static constexpr int32 DEFAULT_MAX_JSON_PAYLOAD_SIZE_KB = 4;

	/**
	 * Intercepts SLM output strings, parses them, audits provenance, and returns a verified state vector update.
	 * @param RawJsonData - The unparsed JSON text string generated by the SLM
	 * @param ActiveImprintBuffer - The authoritative list of memory IDs unsealed by the engine
	 * @param CurrentState - The current operational state vector metrics
	 */
	UFUNCTION(BlueprintCallable, Category = "Ashen Oath|Governance")
	FAshenIdentityCognitiveStateVector ValidateAndCompilePayload(
		const FString& RawJsonData,
		const TArray<FString>& ActiveImprintBuffer,
		const FAshenIdentityCognitiveStateVector& CurrentState
	);

	/**
	 * Evaluates asymmetric exponential memory decay: S(t) = S_0 * e^(-lambda * t)
	 * @param InOutImprints - Authoritative imprint buffer to decay
	 * @param RestCycles - Number of rest cycles elapsed
	 */
	UFUNCTION(BlueprintCallable, Category = "Ashen Oath|Governance")
	void ApplyMemoryDecay(UPARAM(ref) TArray<FAshenImprintRecord>& InOutImprints, int32 RestCycles = 1);

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Ashen Oath|Governance|Balancing")
	UAshenIdentityGovernanceBalanceDataAsset* BalanceDataAsset;
};
